"use client";
import { Montserrat } from "next/font/google";
import "../styles/globals.css";
import { NextUIProvider } from "@nextui-org/react";
// import { Oleo_Script_Swash_Caps } from "next/font/google";

const monst = Montserrat({ subsets: ["latin"] });
// const oleo = Oleo_Script_Swash_Caps({ subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={monst.className}>
        <NextUIProvider>
          <div>{children}</div>
        </NextUIProvider>
      </body>
    </html>
  );
}
